version: '3'

services:
  app:
    image: your-docker-registry/your-image-name:your-tag
    ports:
      - 5000:5000
    environment:
      - CODENAME=thedoctor

  dynamodb:
    image: zestyco/dynamodb-challenge:amd
    ports:
      - 8000:8000
