version: '3'

services:
  app:
    image: lenasavin/interview:zesty
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - dynamodb
    networks:
      - my-network
    

  dynamodb:
    image: zestyco/dynamodb-challenge:amd
    ports:
      - 8000:8000
    networks:
      - my-network
networks:
  my-network:
    driver: bridge